In [ ]:
#Ishrat Amin
#CSCI381
#Professor : Matthew Fried

In [80]:
#https://www.geeksforgeeks.org
#https://numpy.org
#https://www.tutorialspoint.com
#https://www.datasciencemadesimple.com

In [69]:
import numpy as np
import pandas as pd

In [70]:
#1

a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])


In [71]:
print(np.intersect1d(a, b))

[2 4]


In [72]:
#2

arr = np.arange(1,16)
newarr = arr.reshape(3,5)
x=newarr.T
print(x)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [73]:
#3

output = np.sort(x.flatten())
print(output)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [74]:
#4

Three_Darray = arr.reshape(3,1,5)

print(Three_Darray)


[[[ 1  2  3  4  5]]

 [[ 6  7  8  9 10]]

 [[11 12 13 14 15]]]


In [75]:
#5

Two_Darray = np.reshape(Three_Darray, (3, 5))
y=Two_Darray.T
print(y)


[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [76]:
#6

a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])

c=np.setdiff1d(a, b)

print(c)
print(b)


[ 1  7  8 15]
[14  6  3 11 19 12  5]


In [78]:
#7

df = pd.read_csv('Module6_Data.csv')

In [79]:
df

Year  New York City Population  NYC Consumption(Million gallons per day)  \
0   1979                 7102100.0                                    1512.0   
1   1980                 7071639.0                                    1506.0   
2   1981                 7089241.0                                    1309.0   
3   1982                 7109105.0                                    1382.0   
4   1983                 7181224.0                                    1424.0   
5   1984                 7234514.0                                    1465.0   
6   1985                 7274054.0                                    1326.0   
7   1986                 7319246.0                                    1351.0   
8   1987                 7342476.0                                    1447.0   
9   1988                 7353719.0                                    1484.0   
10  1989                 7344175.0                                    1402.0   
11  1990                 7335650.0                                    1424.0   
12  1991                 7374501.0                                    1469.0   
13  1992                 7428944.0                                    1369.0   
14  1993                 7506166.0                                    1368.5   
15  1994                 7570458.0                                    1357.7   
16  1995                 7633040.0                                    1325.7   
17  1996                 7697812.0                                    1297.9   
18  1997                 7773443.0                                    1205.5   
19  1998                 7858259.0                                    1219.5   
20  1999                 7947660.0                                    1237.2   
21  2000                 8008278.0                                    1240.4   
22  2001                 8024963.5                                    1184.0   
23  2002                 8041649.0                                    1135.6   
24  2003                 8058334.5                                    1093.7   
25  2004                 8075020.0                                    1099.5   
26  2005                 8091705.5                                    1138.0   
27  2006                 8108391.0                                    1069.0   
28  2007                 8125076.5                                    1114.0   
29  2008                 8141762.0                                    1098.0   
30  2009                 8158447.5                                    1007.5   
31  2010                 8175133.0                                    1039.0   
32  2011                 8284098.0                                    1021.0   
33  2012                 8361179.0                                    1009.1   
34  2013                 8422460.0                                    1006.1   
35  2014                 8471990.0                                     996.0   
36  2015                 8516502.0                                    1009.0   
37  2016                 8537673.0                                    1002.0   
38  2017                 8622698.0                                     990.2   

    Per Capita(Gallons per person per day)  
0                                      213  
1                                      213  
2                                      185  
3                                      194  
4                                      198  
5                                      203  
6                                      182  
7                                      185  
8                                      197  
9                                      202  
10                                     191  
11                                     194  
12                                     199  
13                                     184  
14                                     182  
15                                     179  
16                                    

In [99]:
##1

Gallons = df['NYC Consumption(Million gallons per day)'].values


In [100]:
print(Gallons)

[1512.  1506.  1309.  1382.  1424.  1465.  1326.  1351.  1447.  1484.
 1402.  1424.  1469.  1369.  1368.5 1357.7 1325.7 1297.9 1205.5 1219.5
 1237.2 1240.4 1184.  1135.6 1093.7 1099.5 1138.  1069.  1114.  1098.
 1007.5 1039.  1021.  1009.1 1006.1  996.  1009.  1002.   990.2]


In [103]:
print(Gallons.max())

1512.0


In [87]:
##2

x= df['Year'].shape

print(x)

(39,)


In [90]:
##3
PerCapita = df['Per Capita(Gallons per person per day)'].values


In [91]:
print(PerCapita)

[213 213 185 194 198 203 182 185 197 202 191 194 199 184 182 179 174 169
 155 155 156 155 148 141 136 136 141 132 137 135 123 127 123 121 119 118
 118 117 115]


In [96]:
print( PerCapita.mean())

160.30769230769232


In [97]:
print(PerCapita.std())

31.51894330370624


In [104]:
#4

pop = df['New York City Population'].values

In [105]:
print(pop)

[7102100.  7071639.  7089241.  7109105.  7181224.  7234514.  7274054.
 7319246.  7342476.  7353719.  7344175.  7335650.  7374501.  7428944.
 7506166.  7570458.  7633040.  7697812.  7773443.  7858259.  7947660.
 8008278.  8024963.5 8041649.  8058334.5 8075020.  8091705.5 8108391.
 8125076.5 8141762.  8158447.5 8175133.  8284098.  8361179.  8422460.
 8471990.  8516502.  8537673.  8622698. ]


In [107]:
pop_diff = np.diff(pop)

In [108]:
print(pop_diff)

[-30461.   17602.   19864.   72119.   53290.   39540.   45192.   23230.
  11243.   -9544.   -8525.   38851.   54443.   77222.   64292.   62582.
  64772.   75631.   84816.   89401.   60618.   16685.5  16685.5  16685.5
  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5 108965.
  77081.   61281.   49530.   44512.   21171.   85025. ]
